- name: Build extension APK
  env:
    ALIAS: key0
    KEY_STORE_PASSWORD: android
    KEY_PASSWORD: android
  run: |
    chmod +x ./gradlew
    ./gradlew :src:all:animeworldindia:assembleRelease --stacktrace --info
